// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 public/earth/earth.gltf 
// Author: savounited (https://sketchfab.com/savounited)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/earth-d92f80d62d0641969d120d6947db5601
// Title: Earth
// */

// import React from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function Model(props) {
//   const { nodes, materials } = useGLTF('/earth.gltf')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
//     </group>
//   )
// }

// useGLTF.preload('/earth.gltf')
